/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_title = 1,
  aux_sym_heading_token1 = 2,
  aux_sym_heading_token2 = 3,
  anon_sym_LF = 4,
  aux_sym_url_token1 = 5,
  anon_sym_BSLASH_RPAREN = 6,
  aux_sym_urltext_token1 = 7,
  anon_sym_BSLASH_RBRACK = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  aux_sym_wikitarget_token1 = 13,
  anon_sym_LBRACK_LBRACK = 14,
  anon_sym_RBRACK_RBRACK = 15,
  sym_tag = 16,
  sym_comment = 17,
  sym_inline_code = 18,
  sym_fenced_code_block = 19,
  sym_text = 20,
  sym_document = 21,
  sym_heading = 22,
  sym_url = 23,
  sym_urltext = 24,
  sym_link = 25,
  sym_wikitarget = 26,
  sym_wikilink = 27,
  aux_sym_document_repeat1 = 28,
  aux_sym_url_repeat1 = 29,
  aux_sym_urltext_repeat1 = 30,
  aux_sym_wikitarget_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_title] = "title",
  [aux_sym_heading_token1] = "heading_token1",
  [aux_sym_heading_token2] = "heading_token2",
  [anon_sym_LF] = "\n",
  [aux_sym_url_token1] = "url_token1",
  [anon_sym_BSLASH_RPAREN] = "\\)",
  [aux_sym_urltext_token1] = "urltext_token1",
  [anon_sym_BSLASH_RBRACK] = "\\]",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_wikitarget_token1] = "wikitarget_token1",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_tag] = "tag",
  [sym_comment] = "comment",
  [sym_inline_code] = "inline_code",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_heading] = "heading",
  [sym_url] = "url",
  [sym_urltext] = "urltext",
  [sym_link] = "link",
  [sym_wikitarget] = "wikitarget",
  [sym_wikilink] = "wikilink",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_url_repeat1] = "url_repeat1",
  [aux_sym_urltext_repeat1] = "urltext_repeat1",
  [aux_sym_wikitarget_repeat1] = "wikitarget_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_title] = sym_title,
  [aux_sym_heading_token1] = aux_sym_heading_token1,
  [aux_sym_heading_token2] = aux_sym_heading_token2,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_url_token1] = aux_sym_url_token1,
  [anon_sym_BSLASH_RPAREN] = anon_sym_BSLASH_RPAREN,
  [aux_sym_urltext_token1] = aux_sym_urltext_token1,
  [anon_sym_BSLASH_RBRACK] = anon_sym_BSLASH_RBRACK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_wikitarget_token1] = aux_sym_wikitarget_token1,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_tag] = sym_tag,
  [sym_comment] = sym_comment,
  [sym_inline_code] = sym_inline_code,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_heading] = sym_heading,
  [sym_url] = sym_url,
  [sym_urltext] = sym_urltext,
  [sym_link] = sym_link,
  [sym_wikitarget] = sym_wikitarget,
  [sym_wikilink] = sym_wikilink,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
  [aux_sym_urltext_repeat1] = aux_sym_urltext_repeat1,
  [aux_sym_wikitarget_repeat1] = aux_sym_wikitarget_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_heading_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_url_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_urltext_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_wikitarget_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_code] = {
    .visible = true,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_urltext] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_wikitarget] = {
    .visible = true,
    .named = true,
  },
  [sym_wikilink] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_urltext_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_wikitarget_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_target = 1,
  field_text = 2,
  field_title = 3,
  field_url = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_target] = "target",
  [field_text] = "text",
  [field_title] = "title",
  [field_url] = "url",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_title, 1},
  [1] =
    {field_title, 2},
  [2] =
    {field_target, 1},
  [3] =
    {field_text, 1},
    {field_url, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 29,
        '#', 23,
        '(', 42,
        ')', 43,
        '<', 31,
        '[', 39,
        '\\', 33,
        ']', 41,
        '`', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == ']') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead == ']') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '`') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '`') ADVANCE(52);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(15);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(53);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '#') ADVANCE(23);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == '`') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_title);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_title);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_heading_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_url_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == ')') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ']') ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_url_token1);
      if (lookahead == '`') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BSLASH_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_urltext_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_urltext_token1);
      if (lookahead == ']') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_wikitarget_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_wikitarget_token1);
      if (lookahead == ']') ADVANCE(38);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_inline_code);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_inline_code);
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_fenced_code_block);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`') ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_heading_token1] = ACTIONS(1),
    [aux_sym_heading_token2] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_url_token1] = ACTIONS(1),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(1),
    [aux_sym_urltext_token1] = ACTIONS(1),
    [anon_sym_BSLASH_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_wikitarget_token1] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_inline_code] = ACTIONS(1),
    [sym_fenced_code_block] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(25),
    [sym_heading] = STATE(2),
    [sym_link] = STATE(2),
    [sym_wikilink] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_heading_token1] = ACTIONS(7),
    [aux_sym_heading_token2] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(13),
    [sym_tag] = ACTIONS(15),
    [sym_comment] = ACTIONS(15),
    [sym_inline_code] = ACTIONS(17),
    [sym_fenced_code_block] = ACTIONS(15),
    [sym_text] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      aux_sym_heading_token1,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_inline_code,
    ACTIONS(21), 4,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
    STATE(3), 4,
      sym_heading,
      sym_link,
      sym_wikilink,
      aux_sym_document_repeat1,
  [31] = 8,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym_heading_token1,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(39), 1,
      sym_inline_code,
    ACTIONS(36), 4,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
    STATE(3), 4,
      sym_heading,
      sym_link,
      sym_wikilink,
      aux_sym_document_repeat1,
  [62] = 4,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(46), 1,
      anon_sym_LF,
    ACTIONS(44), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(42), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [82] = 4,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(52), 1,
      anon_sym_LF,
    ACTIONS(50), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [102] = 3,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(56), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(54), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [119] = 3,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(60), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(58), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [136] = 3,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(64), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(62), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [153] = 3,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(68), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_inline_code,
    ACTIONS(66), 6,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_comment,
      sym_fenced_code_block,
      sym_text,
  [170] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(70), 1,
      aux_sym_urltext_token1,
    ACTIONS(72), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      aux_sym_urltext_repeat1,
  [186] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(76), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(78), 1,
      aux_sym_wikitarget_token1,
    ACTIONS(80), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(12), 1,
      aux_sym_wikitarget_repeat1,
  [202] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(82), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(84), 1,
      aux_sym_wikitarget_token1,
    ACTIONS(86), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(15), 1,
      aux_sym_wikitarget_repeat1,
  [218] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(88), 1,
      aux_sym_urltext_token1,
    ACTIONS(90), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(92), 1,
      anon_sym_RBRACK,
    STATE(14), 1,
      aux_sym_urltext_repeat1,
  [234] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(94), 1,
      aux_sym_urltext_token1,
    ACTIONS(97), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(100), 1,
      anon_sym_RBRACK,
    STATE(14), 1,
      aux_sym_urltext_repeat1,
  [250] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(102), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(105), 1,
      aux_sym_wikitarget_token1,
    ACTIONS(108), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(15), 1,
      aux_sym_wikitarget_repeat1,
  [266] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(110), 1,
      aux_sym_url_token1,
    ACTIONS(112), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      aux_sym_url_repeat1,
  [282] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(116), 1,
      aux_sym_url_token1,
    ACTIONS(118), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_url_repeat1,
  [298] = 5,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(122), 1,
      aux_sym_url_token1,
    ACTIONS(125), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_url_repeat1,
  [314] = 4,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(130), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(132), 1,
      aux_sym_wikitarget_token1,
    STATE(26), 1,
      sym_wikitarget,
  [327] = 4,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(134), 1,
      aux_sym_urltext_token1,
    ACTIONS(136), 1,
      anon_sym_BSLASH_RBRACK,
    STATE(24), 1,
      sym_urltext,
  [340] = 4,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(138), 1,
      aux_sym_url_token1,
    ACTIONS(140), 1,
      anon_sym_BSLASH_RPAREN,
    STATE(28), 1,
      sym_url,
  [353] = 2,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(142), 1,
      sym_title,
  [360] = 2,
    ACTIONS(144), 1,
      sym_title,
    ACTIONS(146), 1,
      aux_sym_heading_token2,
  [367] = 2,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
  [374] = 2,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
  [381] = 2,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(152), 1,
      anon_sym_RBRACK_RBRACK,
  [388] = 2,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(154), 1,
      anon_sym_LPAREN,
  [395] = 2,
    ACTIONS(9), 1,
      aux_sym_heading_token2,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 119,
  [SMALL_STATE(8)] = 136,
  [SMALL_STATE(9)] = 153,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 186,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 218,
  [SMALL_STATE(14)] = 234,
  [SMALL_STATE(15)] = 250,
  [SMALL_STATE(16)] = 266,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 298,
  [SMALL_STATE(19)] = 314,
  [SMALL_STATE(20)] = 327,
  [SMALL_STATE(21)] = 340,
  [SMALL_STATE(22)] = 353,
  [SMALL_STATE(23)] = 360,
  [SMALL_STATE(24)] = 367,
  [SMALL_STATE(25)] = 374,
  [SMALL_STATE(26)] = 381,
  [SMALL_STATE(27)] = 388,
  [SMALL_STATE(28)] = 395,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2, 0, 1),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 2),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikilink, 3, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wikilink, 3, 0, 3),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 4),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 6, 0, 4),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urltext, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikitarget, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikitarget, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urltext, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_urltext_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_urltext_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_urltext_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_wikitarget_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_wikitarget_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_wikitarget_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sylmark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sylmark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
