/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_heading_token1 = 1,
  aux_sym_heading_token2 = 2,
  aux_sym_heading_token3 = 3,
  anon_sym_LF = 4,
  anon_sym_LBRACK = 5,
  aux_sym_link_token1 = 6,
  anon_sym_BSLASH_RBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_LPAREN = 9,
  aux_sym_link_token2 = 10,
  anon_sym_BSLASH_RPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_LBRACK_LBRACK = 13,
  aux_sym_wikilink_token1 = 14,
  anon_sym_RBRACK_RBRACK = 15,
  sym_tag = 16,
  sym_text = 17,
  sym_document = 18,
  sym_heading = 19,
  sym_link = 20,
  sym_wikilink = 21,
  aux_sym_document_repeat1 = 22,
  aux_sym_link_repeat1 = 23,
  aux_sym_link_repeat2 = 24,
  aux_sym_wikilink_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_heading_token1] = "heading_token1",
  [aux_sym_heading_token2] = "heading_token2",
  [aux_sym_heading_token3] = "heading_token3",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACK] = "[",
  [aux_sym_link_token1] = "link_token1",
  [anon_sym_BSLASH_RBRACK] = "\\]",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [aux_sym_link_token2] = "link_token2",
  [anon_sym_BSLASH_RPAREN] = "\\)",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [aux_sym_wikilink_token1] = "wikilink_token1",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_tag] = "tag",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_heading] = "heading",
  [sym_link] = "link",
  [sym_wikilink] = "wikilink",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_link_repeat1] = "link_repeat1",
  [aux_sym_link_repeat2] = "link_repeat2",
  [aux_sym_wikilink_repeat1] = "wikilink_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_heading_token1] = aux_sym_heading_token1,
  [aux_sym_heading_token2] = aux_sym_heading_token2,
  [aux_sym_heading_token3] = aux_sym_heading_token3,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_link_token1] = aux_sym_link_token1,
  [anon_sym_BSLASH_RBRACK] = anon_sym_BSLASH_RBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_link_token2] = aux_sym_link_token2,
  [anon_sym_BSLASH_RPAREN] = anon_sym_BSLASH_RPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [aux_sym_wikilink_token1] = aux_sym_wikilink_token1,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_tag] = sym_tag,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_heading] = sym_heading,
  [sym_link] = sym_link,
  [sym_wikilink] = sym_wikilink,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_link_repeat1] = aux_sym_link_repeat1,
  [aux_sym_link_repeat2] = aux_sym_link_repeat2,
  [aux_sym_wikilink_repeat1] = aux_sym_wikilink_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_heading_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_wikilink_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_wikilink] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_wikilink_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_target = 1,
  field_text = 2,
  field_title = 3,
  field_url = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_target] = "target",
  [field_text] = "text",
  [field_title] = "title",
  [field_url] = "url",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_title, 1},
  [1] =
    {field_title, 2},
  [2] =
    {field_target, 1},
  [3] =
    {field_url, 3},
  [4] =
    {field_text, 1},
  [5] =
    {field_text, 1},
    {field_url, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead == ']') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == ']') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(36);
      END_STATE();
    case 5:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '[') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '[') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead == ']') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(12);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      if (lookahead == '#') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_heading_token2);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_heading_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_heading_token3);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_heading_token3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_link_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_link_token1);
      if (lookahead == ')') ADVANCE(31);
      if (lookahead == ']') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_link_token1);
      if (lookahead == ']') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BSLASH_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_link_token2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_link_token2);
      if (lookahead == ')') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BSLASH_RPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_wikilink_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_wikilink_token1);
      if (lookahead == ']') ADVANCE(25);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_heading_token1] = ACTIONS(1),
    [aux_sym_heading_token2] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_link_token1] = ACTIONS(1),
    [anon_sym_BSLASH_RBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [aux_sym_link_token2] = ACTIONS(1),
    [anon_sym_BSLASH_RPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [aux_sym_wikilink_token1] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(28),
    [sym_heading] = STATE(2),
    [sym_link] = STATE(2),
    [sym_wikilink] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_heading_token1] = ACTIONS(7),
    [aux_sym_heading_token2] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(11),
    [sym_tag] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(7), 1,
      aux_sym_heading_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 2,
      sym_tag,
      sym_text,
    STATE(3), 4,
      sym_heading,
      sym_link,
      sym_wikilink,
      aux_sym_document_repeat1,
  [26] = 7,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      aux_sym_heading_token1,
    ACTIONS(24), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(30), 2,
      sym_tag,
      sym_text,
    STATE(3), 4,
      sym_heading,
      sym_link,
      sym_wikilink,
      aux_sym_document_repeat1,
  [52] = 4,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(37), 1,
      anon_sym_LF,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
    ACTIONS(35), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_text,
  [69] = 4,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(43), 1,
      anon_sym_LF,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
    ACTIONS(41), 3,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
      sym_text,
  [86] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(47), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(45), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [100] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(51), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(49), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [114] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(55), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(53), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [128] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(59), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [142] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(63), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [156] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(67), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(65), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [170] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(71), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [184] = 3,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(75), 2,
      aux_sym_heading_token1,
      anon_sym_LBRACK,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK_LBRACK,
      sym_tag,
      sym_text,
  [198] = 5,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(79), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym_link_repeat2,
    ACTIONS(77), 2,
      anon_sym_LF,
      aux_sym_link_token2,
  [215] = 5,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(86), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      aux_sym_link_repeat2,
    ACTIONS(83), 2,
      anon_sym_LF,
      aux_sym_link_token2,
  [232] = 5,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(93), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      aux_sym_link_repeat2,
    ACTIONS(91), 2,
      anon_sym_LF,
      aux_sym_link_token2,
  [249] = 5,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(99), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      aux_sym_link_repeat2,
    ACTIONS(97), 2,
      anon_sym_LF,
      aux_sym_link_token2,
  [266] = 5,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(93), 1,
      anon_sym_BSLASH_RPAREN,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(15), 1,
      aux_sym_link_repeat2,
    ACTIONS(91), 2,
      anon_sym_LF,
      aux_sym_link_token2,
  [283] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(107), 1,
      aux_sym_link_token1,
    ACTIONS(109), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      aux_sym_link_repeat1,
  [299] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(113), 1,
      aux_sym_link_token1,
    ACTIONS(115), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_link_repeat1,
  [315] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(119), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(121), 1,
      aux_sym_wikilink_token1,
    ACTIONS(123), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(22), 1,
      aux_sym_wikilink_repeat1,
  [331] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(125), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(127), 1,
      aux_sym_wikilink_token1,
    ACTIONS(129), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(23), 1,
      aux_sym_wikilink_repeat1,
  [347] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(131), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(134), 1,
      aux_sym_wikilink_token1,
    ACTIONS(137), 1,
      anon_sym_RBRACK_RBRACK,
    STATE(23), 1,
      aux_sym_wikilink_repeat1,
  [363] = 5,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(139), 1,
      aux_sym_link_token1,
    ACTIONS(142), 1,
      anon_sym_BSLASH_RBRACK,
    ACTIONS(145), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_link_repeat1,
  [379] = 2,
    ACTIONS(147), 1,
      aux_sym_heading_token2,
    ACTIONS(149), 1,
      aux_sym_heading_token3,
  [386] = 2,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(151), 1,
      anon_sym_LPAREN,
  [393] = 2,
    ACTIONS(3), 1,
      aux_sym_heading_token2,
    ACTIONS(153), 1,
      aux_sym_heading_token3,
  [400] = 2,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
  [407] = 2,
    ACTIONS(105), 1,
      aux_sym_heading_token2,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 86,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 128,
  [SMALL_STATE(10)] = 142,
  [SMALL_STATE(11)] = 156,
  [SMALL_STATE(12)] = 170,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 198,
  [SMALL_STATE(15)] = 215,
  [SMALL_STATE(16)] = 232,
  [SMALL_STATE(17)] = 249,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 283,
  [SMALL_STATE(20)] = 299,
  [SMALL_STATE(21)] = 315,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 347,
  [SMALL_STATE(24)] = 363,
  [SMALL_STATE(25)] = 379,
  [SMALL_STATE(26)] = 386,
  [SMALL_STATE(27)] = 393,
  [SMALL_STATE(28)] = 400,
  [SMALL_STATE(29)] = 407,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 2),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikilink, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wikilink, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 4),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wikilink, 3, 0, 3),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wikilink, 3, 0, 3),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 5),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 6, 0, 6),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 6, 0, 6),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_link_repeat2, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_wikilink_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_wikilink_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_wikilink_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_link_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [155] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sylmark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sylmark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
